name: Build Windows App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Prepare external files
      run: |
        mkdir dist\templates
        copy templates\* dist\templates\
        mkdir dist\assets
        copy assets\* dist\assets\
        
    - name: Build application
      run: |
        pyinstaller --onefile --windowed --name GeneratorNormirovannoe --icon "assets/msecurity_logo.ico" --add-data "templates/*;templates" --add-data "assets/*;assets" main.py
        
    - name: Verify build
      run: |
        dir dist\
        dir dist\templates\
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GeneratorNormirovannoe
        path: |
          dist/GeneratorNormirovannoe.exe
          dist/templates/
          dist/assets/
